# fly.toml app configuration file generated for utilifyapi on 2023-07-12T12:53:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "utilifyapi"
primary_region = "otp"

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 0
  processes = ["app"]
